# ===== FILE: docker-compose.yml =====
version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: rkat_postgres
    environment:
      POSTGRES_DB: rkat_bpkh
      POSTGRES_USER: rkat_user
      POSTGRES_PASSWORD: rkat_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - rkat_network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: rkat_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - rkat_network

  # FastAPI Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: rkat_backend
    environment:
      DATABASE_URL: postgresql://rkat_user:rkat_password@postgres:5432/rkat_bpkh
      REDIS_URL: redis://redis:6379
      SECRET_KEY: dev-secret-key-change-in-production
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app
      - ./uploads:/app/uploads
    networks:
      - rkat_network
    restart: unless-stopped

  # Streamlit Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: rkat_frontend
    environment:
      API_BASE_URL: http://backend:8000
    ports:
      - "8501:8501"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    networks:
      - rkat_network
    restart: unless-stopped

  # Nginx Reverse Proxy (optional)
  nginx:
    image: nginx:alpine
    container_name: rkat_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - backend
      - frontend
    networks:
      - rkat_network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  rkat_network:
    driver: bridge
