# .streamlit/config.toml
# Configuration for Streamlit Cloud deployment

[global]
# Development mode
developmentMode = false

[server]
# Server configuration
port = 8501
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 200

# Security headers
enableStaticServing = false

[browser]
# Browser configuration
gatherUsageStats = false
serverAddress = "localhost"

[theme]
# App theme
primaryColor = "#4B0082"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[logger]
# Logging configuration
level = "info"

[client]
# Client configuration
caching = true
showErrorDetails = false